frase = "Curso em Vídeo Python"
print(frase[3:13])
print(frase[1:15])
print(frase[1:15:2])
print(frase[1::2])
print(frase[::2])
print(len(frase))
print(frase.count("o"))
print(frase.count("o", 0, 13))
print(frase.find("deo"))
print(frase.find("Android"))
print("Curso" in frase)
print(frase.replace("Python", "Android"))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
